import { useMsal } from "@azure/msal-react";
import React from "react";
import { b2cPolicies } from "../../authConfig";
import CommonHeader from "../../components/Header/CommonHeader";
import { getAccessCode, getAccessToken, setUserFlow } from "../../services";
import "../Privacy/index.css";
const Terms = () => {
  const hostUrl = window.location.origin;
  const { instance } = useMsal();
  const isAccessedTerms = getAccessCode();
  const isAccessTokenTerms = getAccessToken()

  const handleLoginTerms = () => {
    setUserFlow('signInUp');
    instance.loginRedirect({
      authority: b2cPolicies.authorities.signUpSignInUp.authority,
      clientId: process.env.REACT_APP_MSAL_ID,
      redirectUri: "/",
      postLogoutRedirectUri: "/",
      knownAuthorities: [],
    });
  }

  const handleSignupTerms = () => {
    setUserFlow('signUp');
    instance.loginRedirect({
      authority: b2cPolicies.authorities.signUp.authority,
      clientId: process.env.REACT_APP_MSAL_ID,
      redirectUri: "/",
      postLogoutRedirectUri: "/",
      knownAuthorities: [],
    });
  }

  return (
    <>
      {isAccessedTerms && !isAccessTokenTerms && (
        <CommonHeader handleSignup={handleSignupTerms} handleLogin={handleLoginTerms} />
      )}

      <div className="bg-gray-2 privacy">
        <div className="pt-18 md:pt-22.5 all-stories-page-wrap main-wrapper mx-auto w-full">
          <div className="bg-white rounded-lg p-7 mb-9">
            <h1 className="font-bold text-xl text-black">Terms of Service</h1>
            <h3 className="font-bold text-base text-black mt-4 mb-4">World Archives Holdings LLC</h3>

            <h2 className="font-bold text-base text-black">1. Welcome and Introduction</h2>
            <p className="text-sm text-black mb-4">Welcome to the World Archives network of tools and services made available by World Archives. Our services help our subscribers power their historical and genealogical research, make family connections, and build their family trees. The Services includes the software, apps, web interface, and content offered in connection with the software, documentation, and online tools, whether they are accessed through the use of a mobile device, computer, or other method (individually and together, the “Services”).</p>
            <p className="text-sm text-black mb-4">The term “Services” covers World Archives’ entire network of Services, which works cooperatively by sharing information within the network to provide you a convenient and integrated experience as you add more Services. The term also includes any help desk and support services we offer, as well as any new features which augment or enhance the current Services, including the release of new features or products.</p>
            <p className="text-sm text-black mb-4">We hope you will carefully read through these Terms of Service (“Agreement”), since it is a binding agreement between you and World Archives Holdings LLC (“Company”, “we”,“us”,“our”). It is effective on the date you click “I Accept” or a similar indication of your intent to enter into this Agreement with us.</p>
            <p className="text-sm text-black mb-4">Specific provisions related to pricing, payment terms, and other matters related to this Agreement may be set forth in an online document, purchase order or any other document that is executed by both parties (“Order Form”). However, the terms of an Order Form other than an online document provided by us may not change the provisions of this Agreement unless the Order Form specifically calls out the provisions changed and is signed by both parties. No order form, purchase agreement, or any other document generated by you may change the terms of this Agreement, even if it is made expressly conditioned upon our acceptance of the additional document.</p>
            <p className="text-sm text-black mb-4">
              World Archives complies with the requirements of the General Data Protection Regulation effective in Europe and has adopted the terms of the Data Processing Agreement located at <a href={`${hostUrl}/dpa`}>{`${hostUrl}/dpa`}</a> and incorporated by reference as if set forth in full herein.
            </p>
            <p className="text-sm text-black mb-4">
              By entering into this Agreement with us, you also agree to the terms of our Privacy Policy <a href={`${hostUrl}/privacy`}>{`${hostUrl}/privacy`}</a> and the terms and conditions of any community rules or other document that we may require you to approve when you sign up for new Services.
            </p>
            <p className="text-sm text-black mb-4">If you are between the ages of 13 and 18, you may use the Services with your parent's or guardian's permission. Children under the age of 13 are not permitted to use any Services. We do not knowingly seek or collect any personal information directly from children under the age of 13. If we become aware that we have unknowingly collected any personal data directly from a child under the age of 13, we will take commercially reasonable efforts to delete such data from our system.</p>

            <h2 className="font-bold text-base text-black">2. Software, Fees, Chargebacks, Refunds, and Term</h2>
            <p className="text-sm text-black mb-4">The Services are made available to you on a software-as-a-service (SaaS) basis through one or more web portals or mobile applications. The Services may be modified by us in our sole discretion, with or without notice, at any time. If we have modified the Services in a manner that materially reduces the value you obtain from the Services (e.g., by removing specific functionality without replacing it with substantially similar or improved functionality) then you, as your sole remedy, may terminate this Agreement. Your continued receipt and use of the Services following the modification to the Services shall conclusively demonstrate your acceptance of such modification.</p>
            <p className="text-sm text-black mb-4">You agree to pay any fees set forth in an Order Form (“Fee”) upon the terms described in the Order Form. Prices may be changed by Company at any time, and each renewal of your subscription will be at the price that you were originally charged for that subscription when you subscribed unless otherwise stated or there is a change in your subscription price. Company shall provide you with reasonable notice of any change in prices prior to the effective date of the new pricing by email or other reasonable means such as a notice on the pertinent Services or in usual subscriber communications.</p>
            <p className="text-sm text-black mb-4">When you sign up using a credit card or other payment method, you authorize us to make the charges disclosed to you at the time you sign up, including recurring payments, where applicable.</p>
            <p className="text-sm text-black mb-4">If you initiate a chargeback or otherwise reverse a payment made with your Payment Method, we will terminate your membership immediately. If we successfully dispute the reversal, and the reversed funds are returned to us, you are not entitled to a refund or to have your membership reinstated.</p>
            <p className="text-sm text-black mb-4">
              Daily, Weekly, or Monthly subscriptions are never eligible for a refund. For quarterly, semi-annual or annual subscriptions, you may cancel within the first 30 days of a new subscription or within seven days of your renewal date and receive a full refund if you do not view any newspaper, clipping, genealogy record or obituary image during that period. Viewing any of our content voids your eligibility to receive a refund. If you cancel your subscription and are not eligible for a refund you will retain access to the Services until your subscription expires. All refunds will be given to the original credit card on which the purchase was made. Please allow a reasonable time for the refund to be credited to your account by your credit card company.
            </p>
            <p className="text-sm text-black mb-4">The term of this Agreement shall be the period set forth in the Order Form, or if no term is set forth in the Order form, a period of one year. You may opt out of renewing the term by logging into the website to which you subscribed any time before the renewal date, clicking Account Settings and following the cancellation instructions there.</p>
            <p className="text-sm text-black mb-4">If we believe, in our sole discretion, that you are in breach of this Agreement or are acting inconsistently with the letter or spirit of this Agreement, we may limit, suspend or terminate your access to the Services. In such a case, no portion of your Fee will be refunded.</p>

            <h2 className="font-bold text-base text-black">3. License and Acceptable Use</h2>
            <p className="text-sm text-black mb-4">
              Company hereby grants you, subject to your compliance with this Agreement, a limited non-exclusive, non-sublicensable, non-transferable, license to use the Services. You may not download any portion of the Services or use of any Services other than for the purposes described in this Agreement or an Order Form. You may not use any data mining, robots, or similar data gathering tools or otherwise exploit your access to the Services for any commercial purpose, except as you provide professional genealogical services to third parties on an individual basis. You may not use any of the trademarks, logos, or other proprietary graphics without express written permission, which may denied in Company’s absolute discretion. Company’s logos and product and service names are trademarks of
              Company. All other trademarks appearing on the website or in connection with the Services are trademarks of their respective owners, and our reference to them does not imply or indicate any approval or endorsement by their owners unless such approval or endorsement is expressly made.
            </p>

            <p className="text-sm text-black">In addition to any other things that might constitute a misuse of the Services, you must not, and must not attempt to do the following things:</p>
            <div className="my-2">
              <ol className="footer-list-disc">
                <li className="text-sm text-black ml-7">modify, alter, tamper with, repair or otherwise create derivative works of any of the Services;</li>
                <li className="text-sm text-black ml-7">reverse engineer, disassemble or decompile the software used to provide or access the Services, or attempt to discover or recreate the source code used to provide or access the Services, except and only to the extent that the applicable law expressly permits doing so;</li>
                <li className="text-sm text-black ml-7">use the Services for research or benchmarking or any related endeavor or taking any other action with the intent of creating a competing or similar product;</li>
                <li className="text-sm text-black ml-7">use the Services in any manner or for any purpose other than as expressly permitted by this Agreement, our privacy policy, or any other policy, instruction or terms applicable to the Services;</li>
                <li className="text-sm text-black ml-7">use any technical means to scrape or crawl any of the Services for the purpose of retrieving, saving, downloading, benchmarking, or indexing any of the information, data, or images made available from the Services, including without limitation Our Content (defined below);</li>
                <li className="text-sm text-black ml-7">sell, lend, rent, resell, lease, sublicense or otherwise transfer any of the rights granted to you with respect to the Services to any third party;</li>
                <li className="text-sm text-black ml-7">remove, obscure or alter any proprietary rights notice pertaining to the Services;</li>
                <li className="text-sm text-black ml-7">access or use the Services in a way intended to improperly avoid incurring fees or exceeding usage limits or quotas;</li>
                <li className="text-sm text-black ml-7">
                  use the Services to: (i) engage in any unlawful or fraudulent activity or perpetrate a hoax or engage in phishing schemes or forgery or other similar falsification or manipulation of data; (ii) send unsolicited or unauthorized junk mail, spam, chain letters, pyramid schemes or any other form of duplicative or unsolicited messages, whether commercial or otherwise; (iii) advertise or promote a commercial product or service that is not available through Company; (iv) store or transmit inappropriate content, such as content: (1) containing unlawful, defamatory, threatening, pornographic, abusive, libelous or otherwise objectionable material of any kind or nature, (2) containing any material that encourages conduct that could constitute a criminal offense, or (3) that violates
                  the intellectual property rights or rights to the publicity or privacy of others; (v) store or transmit any content that contains or is used to initiate a denial of service attack, software viruses or other harmful or deleterious computer code, files or programs such as Trojan horses, worms, time bombs, cancelbots, or spyware; or (vi) abuse, harass, stalk or otherwise violate the legal rights of a third party;
                </li>
                <li className="text-sm text-black ml-7">interfere with or disrupt servers or networks used by Company to provide the Services or used by other users to access the Services, or violate any third party regulations, policies or procedures of such servers or networks or harass or interfere with another user’s full use and enjoyment of any of the Services;</li>
                <li className="text-sm text-black ml-7">access or attempt to access Company’s other accounts, computer systems or networks not covered by this Agreement, through password mining or any other means;</li>
                <li className="text-sm text-black ml-7">cause, in Company’s sole discretion, inordinate burden on the Services or Company’s system resources or capacity; or</li>
                <li className="text-sm text-black ml-7">share passwords or other access information or devices or otherwise authorize any third party to access or use the Services.</li>
              </ol>
            </div>

            <h2 className="font-bold text-base text-black">4. Received Materials</h2>
            <p className="text-sm text-black mb-4">
              If you send us any feedback, comments, materials, or letters including, without limitation, questions, comments, suggestions, criticisms or the like (“Received Materials”), those Received Materials may be deemed by us to be non-confidential and free of any claims of proprietary or personal rights. Company shall have no obligation of any kind with respect to such Received Materials, and Company will be free to reproduce, use, disclose, exhibit, display, transform, edit, abridge, create derivative works from and/or distribute the Received Materials without limitation or restriction. Furthermore, Company is free to use any ideas, concepts, know-how, or techniques contained in any communication you send to Company for any purpose whatsoever, including, but not limited to,
              developing, manufacturing, and marketing products using such information or ideas, without compensation or any other obligations to anyone, including you.
            </p>

            <h2 className="font-bold text-base text-black">5. Accounts and End Users</h2>
            <p className="text-sm text-black mb-4">
              5.1. In order to use the Services, you must create an account (“Account”). You will receive credentials for your Account on a “single sign-on” basis, meaning that a single set of credentials will allow you to access each of the Services in our network. You must not allow anyone other than yourself or authorized employees or agents acting on your behalf (each, an “End User”) to access or use your Account. You acknowledge and agree: (i) to provide accurate and complete Account and login information; (ii) to keep, and ensure that End Users keep all Account login details and passwords secure at all times; (iii) you remain solely responsible and liable for the activity that occurs in connection with your Account, (iv) that the Account login details may only be used by End Users; and
              (v) to promptly notify Company in writing if you become aware of any unauthorized access or use of your Account or the Service.
            </p>
            <p className="text-sm text-black mb-4">
              5.2. World Archives offers three types of accounts: Consumer Access, Institutional Access, and Institutional Sub-Access. Consumer Access accounts are intended for individuals carrying out their own personal activities using the Services. Institutional Access accounts are intended for public libraries, schools, government entities, and other public or private institutions where patrons or other users will access the Services using the institution’s credentials for purposes approved by the institution. Institutional Sub-Access accounts are intended for individuals carrying out their own personal activities using the Services while authenticated through the host institution. If you are anyone other than an individual using the Services for your own personal purposes, you must sign
              up for an Institutional Access subscription. You may not rent, sell, transfer, or otherwise share your credentials with any third party or take any other action that has the impact of allowing any third parties who should be acquiring their own account to access the Services. World Archives may audit your account at any time and charge you in arrears for usage that should have been charged as an Institutional Access subscription.
            </p>

            <h2 className="font-bold text-base text-black">6. Content</h2>
            <p className="text-sm text-black mb-4">6.1. Our Content. The Services include content such as indexes, videos, photographs, documents, records, newspaper clippings, genealogical records, and other information provided by World Archives, either directly or through its partnerships and licenses with other entities or individuals (“Our Content”). Our Content belongs solely to us, even when it is in the public domain. You may use Our Content only for your own personal non-commercial purposes (except as you provide professional genealogical services to third parties on an individual basis). You agree that you will not redistribute or sell any portion of Our Content or remove any proprietary notices or World Archive branding from any of Our Content that you download or print.</p>
            <p className="text-sm text-black mb-4">Each of the Services is protected by copyright as a collective work or compilation, pursuant to U.S. copyright laws, international conventions, and other copyright laws. The trademarks, service marks, and logos contained in the Services are owned by or licensed to Company. We and our licensors retain title, ownership, and all other rights and interests in and to all of Our Content in the Services.</p>
            <p className="text-sm text-black mb-4">6.2. Your Content. When you use the Services, you will have an opportunity to upload or attach various items of information, such as indexes, records, videos, photographs, documents, newspaper clippings, stories about a relative, and comments you make in community discussions and on clipped content (“Your Content”). For purposes of clarity, Your Content does not include your name, contact information, or payment or other information related to you individually apart from the Services.</p>
            <p className="text-sm text-black">6.3. Ownership and Usage of Your Content. Your Content belongs to you, but you agree that we may use Your Content as provided in Section 6.3.d below. With respect to Your Content, you agree as follows:</p>
            <div className="my-2">
              <ol className="footerlist-alpha">
                <li className="text-sm text-black ml-12">Your gathering and use of Your Content is in compliance with any applicable Data Protection Laws and Regulations (defined below);</li>
                <li className="text-sm text-black ml-12">You are responsible for Your Content and have sufficient rights to Your Content to post it in the Services; and</li>
                <li className="text-sm text-black ml-12">You will cooperate with us in any effort to establish your ownership or other rights in Your Content.</li>
                <li className="text-sm text-black ml-12">
                  You will have an opportunity to mark any of Your Content as “private,” and any of Your Content that is so marked will not be shared or made available to the public. Any of Your Content that you have shared (by posting to your profile, connecting, clipping, tagging, uploading, or otherwise making public) using the Services without marking it as “private” may be made available by Company to other users of the Services, and such use may continue after termination of your agreement with Company. You grant Company a fully sublicensable, perpetual, worldwide, royalty-free license to host, store, copy, publish, distribute, provide access to, create derivative works of, and otherwise use such of Your Content in any manner we deem appropriate on or through any media or medium and
                  with any technology or devices. This includes the right for Company to copy, display, and index Your Content. Company will own the indexes it creates and will have the right to continue to use Your Content after this Agreement is terminated, but only as necessary for us to provide and improve the Services. Notwithstanding the foregoing, any of Your Content that you delete without having shared it will be deleted, but once you share Your Content with others, we will not be able to delete it.
                </li>
                <li className="text-sm text-black ml-12">We are not responsible for Your Content, nor do we endorse any opinion contained in any of Your Content. YOU AGREE THAT IF ANYONE BRINGS A CLAIM AGAINST US RELATED TO YOUR CONTENT, THEN, TO THE EXTENT PERMISSIBLE UNDER LOCAL LAW, YOU WILL DEFEND, INDEMNIFY AND HOLD US HARMLESS FROM AND AGAINST ALL DAMAGES, LOSSES, AND EXPENSES OF ANY KIND (INCLUDING REASONABLE ATTORNEY FEES AND COSTS) ARISING OUT OF OR RELATED TO SUCH CLAIM.</li>
              </ol>
            </div>
            <p className="text-sm text-black mb-4">
              6.4. Data Protection Laws and Regulations. You acknowledge that Your Content may contain personally identifying information or personal data, as defined by the applicable laws which govern the use of data relating to identified or identifiable nature persons residing in the EU and/or the state of California in the United states, including the laws of the European Union (“EU”) Data Protection Act 1998, the EU General Data Protection Regulation (“GDPR”), and the California Consumer Protection Act effective as of January 1, 2020, as each of these laws are amended or replaced from time to time, and any other foreign or domestic laws to the extent that they are applicable to the personally identifiable or personal data you upload, transmit, post or process while using the Services
              (“Data Protection Laws and Regulations”).
            </p>
            <p className="text-sm text-black mb-4">6.5. Backup. You acknowledge that: (i) the Services do not operate as an archive or file storage service and we do not store or backup Your Content for the purpose of providing a back-up service (although we may do back-ups for our own purposes); (ii) you are solely responsible for any backup of Your Content; and (iii) you will lose access to any of Your Content that you delete.</p>
            <p className="text-sm text-black mb-4">
              6.6. Internet Security. You understand and acknowledge that the Internet and communications over it may not be secure, and that connecting to it provides the opportunity for unauthorized access to computer systems, networks, and all data stored therein. The information and data transmitted through the Internet (including, without limitation, Your Content) or stored on any equipment through which Internet information is transmitted may not remain confidential and Company makes no representation or warranty regarding privacy, security, authenticity, non-corruption or destruction of any such information. Use of any information transmitted or obtained over the Internet is at your own risk and Company shall not be responsible to you for any adverse consequence or loss whatsoever
              from use of the Internet.
            </p>
            <p className="text-sm text-black mb-4">6.7. Monitoring. We may, but we have no obligation to, monitor, review, or edit Your Content. In all cases, we reserve the right to remove or disable access to any of Your Content for any or no reason, including but not limited to, Your Content that, in our sole discretion, violates the Agreement. We may take these actions without prior notification to you or any third party. Removal or disabling of access to Your Content shall be at our sole discretion, and we do not promise to remove or disable access to any of Your Content.</p>
            <p className="text-sm text-black mb-4">
              6.8. Requests to Remove Information. Certain of the information made available using our Services consists of newspaper articles and other publicly available information that has been published by third parties in the exercise of their free speech rights under applicable law, and we are simply providing access to such articles and other information. We are not the publisher or owner of that information, and our policy is not to remove references to individuals that may contain personal information, because that would infringe upon the free speech rights of others. If there is any publicly available information that you feel endangers the physical safety of you or other persons, you may submit a request that we remove access to that information at{" "}
              <a href="mailto:customerservice@storied.com">customerservice@storied.com</a>. We will make the determination of whether to remove access to that information in our sole and absolute discretion and without any liability whatsoever to you or others.
            </p>

            <h2 className="font-bold text-base text-black">7. Digital Communications</h2>
            <p className="text-sm text-black mb-4">When you visit our website or send e-mails to us, you are communicating with us electronically, and you consent to receive communications from us electronically. We will communicate with you by e-mail or by posting notices on our website. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.</p>

            <h2 className="font-bold text-base text-black">8. Digital Millennium Copyright Act</h2>
            <p className="text-sm text-black mb-4">We are careful to protect the intellectual property rights of others, and we comply with the provisions of the Digital Millennium Copyright Act where it applies to us.</p>
            <p className="text-sm text-black mb-4">If an individual feels that content that has been provided to public areas of our Services belongs to that individual or that it is covered by a copyright of someone other than the submitter, that individual should take note that we are simply a distributor of that content and that the individual who submitted the content would be the party violating any intellectual property rights, not us. However, we will respond to substantiated claims of violation in accordance with the Digital Millennium Copyright Act (DMCA).</p>
            <p className="text-sm text-black mb-4">We have implemented notice and takedown procedures which apply to content reported and removed for violating U.S. copyrights. In appropriate circumstances and at our sole discretion, we may terminate the accounts of users who have been identified as repeat infringers of any intellectual property rights of others, including copyright. A person who believes they have a claim under copyright should send a claim of copyright violation to:</p>
            <p className="text-sm text-black mb-4">
              <b>Attention</b>: World Archives DMCA Designated Agent <br />
              Steve Dalton <br />
              Email: sdalton@worldarchives.com <br />
              Work Phone: 1-800-848-0224 x 104 <br />
              Instructions on designating an agent and a registration system for doing so can be found at <br />
              <a href="https://www.copyright.gov/dmca-directory">https://www.copyright.gov/dmca-directory</a>
            </p>
            <p className="text-sm text-black">When submitting a claim, all of the following must be included:</p>
            <div className="my-2">
              <ol className="footer-list-disc">
                <li className="text-sm text-black ml-7">Identification of the copyrighted work claimed to be infringed, and the basis of the claim</li>
                <li className="text-sm text-black ml-7">Identification of the material which is claimed to be infringing, including the URL</li>
                <li className="text-sm text-black ml-7">Full contact information on the claimed copyright owner or other claimant (who must have a license which is being infringed or other standing to make the claim), including name, address, telephone, fax, and email information</li>
                <li className="text-sm text-black ml-7">A statement that the claimant believes in good faith that the use of the allegedly infringing material is not authorized by the copyright owner, its agent or the law</li>
                <li className="text-sm text-black ml-7">A statement, under penalty of perjury, that the information sent is accurate and the complaining party is the owner or an authorized agent of the owner</li>
                <li className="text-sm text-black ml-7">A physical or electronic signature of the claiming party</li>
              </ol>
            </div>

            <h2 className="font-bold text-base text-black">9. Third Party Applications and White-Labeled Integrations</h2>
            <p className="text-sm text-black mb-4">9.1 The Services may be integrated with third-party applications, websites, and services (“Third Party Applications”) to make available content, products, and/or services to you. These Third- Party Applications may have their own terms and conditions of use and privacy policies and your use of these Third-Party Applications will be governed by and subject to such terms and conditions and privacy policies. You understand and agree that we do not endorse and are not responsible or liable for the behavior, features, or content of any Third-Party Application or for any transaction you may enter into with the provider of any such Third-Party Applications.</p>
            <p className="text-sm text-black mb-4">9.2 We may make other services available to you that are offered by third parties but white labeled by us, meaning that we provide the services under our own name and that your contractual relationship is with us, but that we use a third party to provide those services. For example, we may offer an opportunity for you to organize and publish Your Content in a book or other format using a third party service. When you sign up for such a service, you agree that we may share Your Content with such third-party providers for the sole purpose of rendering the service in question.</p>

            <h2 className="font-bold text-base text-black">10. Advertising and Publicity</h2>
            <p className="text-sm text-black mb-4">Company shall be entitled to refer to you as a customer of Company and as a user of the Service, directly or indirectly, in any advertisement, news release, or publication, and may use your trade names and trademarks in connection with such usage, subject to any reasonable limitations or guidelines you may impose.</p>

            <h2 className="font-bold text-base text-black">11. Warranty Disclaimer</h2>
            <p className="text-sm text-black mb-4">
              Company shall not be held responsible or liable for any actions taken by you, your End Users, either wholly or in part, based on the information provided to Company by you, your End Users, or any third party, or for any loss, damage, expense or injury resulting from any transactions conducted by you or your End Users with any third party as a result, by way of or through the use of the Service. THE SERVICES, INCLUDING WITHOUT LIMITATION, ALL SOFTWARE, CONTENT, AND INFORMATION PROVIDED AS PART OF THE SERVICE, ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS, AND WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. You acknowledge that you may learn information about your relatives and/or ancestors that is surprising or alarming, and you agree that Company shall not be
              responsible for anything resulting from such discovery. You assume all responsibility for the selection of the Service to achieve your intended results.
            </p>
            <p className="text-sm text-black mb-4">
              COMPANY HEREBY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED, IMPLIED WARRANTIES OF MERCHANTABILITY, TITLE, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. COMPANY DOES NOT WARRANT THAT THE SERVICES OR OUR CONTENT WILL BE COMPLETE, ACCURATE, SECURE, UNINTERRUPTED, ERROR FREE, FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS OR THAT DEFECTS WILL BE CORRECTED. COMPANY DOES NOT OFFER A WARRANTY OR MAKE ANY REPRESENTATION REGARDING ANY SOFTWARE, CONTENT, INFORMATION, OR RESULTS THAT YOU OBTAIN THROUGH THE SERVICE. YOUR USE OF AND RELIANCE UPON THE SERVICES IS ENTIRELY AT YOUR SOLE DISCRETION AND RISK, AND COMPANY SHALL HAVE NO RESPONSIBILITY OR LIABILITY WHATSOEVER TO YOU IN CONNECTION WITH ANY OF THE FOREGOING. YOU AGREE THAT WE WILL NOT BE HELD
              RESPONSIBLE FOR ANY CONSEQUENCES THAT MAY RESULT FROM THIRD PARTY’S HARDWARE, SOFTWARE, COMMUNICATIONS SERVICES OR MATERIALS, OR FROM TECHNICAL PROBLEMS, INCLUDING WITHOUT LIMITATION IN CONNECTION WITH, THE INTERNET (SUCH AS SLOW CONNECTIONS, TRAFFIC CONGESTION, DELAYS OR INTERRUPTIONS OR OVERLOAD OF OUR OR OTHER SERVERS) ANY TELECOMMUNICATIONS, INTERNET PROVIDERS OR OTHER THIRD PARTY SERVICE PROVIDERS. Applicable law may not allow the exclusion of certain warranties, so to that extent the above exclusions may not apply.
            </p>

            <h2 className="font-bold text-base text-black">12. Limitation of Liability</h2>
            <p className="text-sm text-black mb-4">
              COMPANY SHALL NOT BE LIABLE FOR ANY INDIRECT, EXEMPLARY, SPECIAL, PUNITIVE, CONSEQUENTIAL, OR INCIDENTAL DAMAGES OF ANY KIND (INCLUDING WITHOUT LIMITATION LOST PROFITS OR REVENUE, LOSS OF GOODWILL, DATA LOSS, WORK STOPPAGE, OR COMPUTER FAILURE, DELAY OR MALFUNCTION) ARISING OUT OF THE ORDER FORM AND/OR THIS AGREEMENT OR IN CONNECTION WITH THE USE OF OR INABILITY TO USE THE SERVICE OR OUR CONTENT, EVEN IF THE PARTY AGAINST WHOM A CLAIM IS ASSERTED HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT SHALL THE AGGREGATE LIABILITY OF COMPANY FOR ANY CLAIMS AND DAMAGES ARISING FROM OR OUT OF THE ORDER FORM AND/OR THIS AGREEMENT OR IN CONNECTION WITH THE USE OF OR THE INABILITY TO USE THE SERVICES OR OUR CONTENT (WHETHER ARISING UNDER CONTRACT, TORT, NEGLIGENCE, STRICT
              LIABILITY OR OTHERWISE) EXCEED $500.00. Applicable law may not allow the exclusion or limitation of liability, so to that extent the above limitations or exclusions may not apply.
            </p>

            <h2 className="font-bold text-base text-black">13. Copyright and Title</h2>
            <p className="text-sm text-black mb-4">The Services and all copyrights, trade secrets and other proprietary rights therein, including any derivative work, are, and will remain the sole property of Company, regardless of the use made by you; and are protected by certain United States and international copyright laws and trademark laws. The Services are licensed, not sold, to you. This Agreement confers no title of ownership in the Services and are not a sale of any rights in the Services, including any intellectual property rights related thereto.</p>

            <h2 className="font-bold text-base text-black">14. Assignment and Sale</h2>
            <p className="text-sm text-black mb-4">Company may assign this Agreement and any of its rights hereunder to any third party in its sole and absolute discretion and without restriction.</p>

            <h2 className="font-bold text-base text-black">15. Service Limitations and Modifications</h2>
            <p className="text-sm text-black mb-4">
              Company will make reasonable efforts to keep the Services operational. However, certain technical difficulties or maintenance may, from time to time, result in temporary interruptions. To the extent permissible under applicable law, we reserve the right, periodically and at any time, to modify or discontinue, temporarily or permanently, functions and features of the Services, with or without notice, all without liability to you, except where prohibited by law, for any interruption, modification, or discontinuation of the Services or any function or feature thereof. You understand and agree that Company has no obligation to maintain, support, upgrade, or update the Services, or to provide all or any specific content through the Services. Company and/or the owners of any Content
              may, from time to time, remove any such Content without notice to the extent permitted by applicable law.
            </p>

            <h2 className="font-bold text-base text-black">16. Governing Law and Jurisdiction</h2>
            <p className="text-sm text-black mb-4">
              The Services are operated by Company from its offices in Utah in the United States. The validity, construction, and performance of this Agreement shall be governed by and construed in accordance with the laws of the State of Utah, without reference to choice of law principles. You expressly agree that exclusive jurisdiction for any claim or dispute with Company, this Agreement, or relating in any way to your use of the Services resides in the federal and state courts located in the State of Utah. You agree to and consent to jurisdiction and venue in the State of Utah. You agree to waive any defense pertaining to jurisdiction and venue. In the event any provision hereof shall be held by a tribunal of competent jurisdiction to be contrary to law, the remaining provisions of this
              Agreement shall remain in full force and effect.
            </p>

            <h2 className="font-bold text-base text-black">17. Attorney Fees</h2>
            <p className="text-sm text-black mb-4">In case of an action to enforce any rights or conditions of this Agreement, or appeal from said proceeding, it is mutually agreed that the losing party in such suit, action, proceeding or appeal shall pay the prevailing party’s reasonable attorney fees and costs incurred.</p>

            <h2 className="font-bold text-base text-black">18. Entire Agreement</h2>
            <p className="text-sm text-black mb-4">This Agreement is a binding contract and constitute the entire agreement and understanding of the parties, whether oral or written, relating to the subject matter hereof; are intended as the parties’ final expression and complete and exclusive statement of the terms hereof, superseding all prior or contemporaneous agreements, representations, communications, and understandings, whether written or oral; and may be amended or modified only by an instrument in writing signed by both parties.</p>

            <h2 className="font-bold text-base text-black">19. Non-Waiver</h2>
            <p className="text-sm text-black mb-4">No waiver of any provision of this Agreement shall constitute a waiver of any other provision, whether or not similar, nor shall any waiver constitute a continuing waiver. Failure to enforce any provision of this Agreement shall not operate as a waiver of such provision or any other provision or of the right to enforce such provision or any other provision.</p>

            <h2 className="font-bold text-base text-black">20. Severability; Binding Effect</h2>
            <p className="text-sm text-black mb-4">If any provision of this Agreement shall be invalid or unenforceable in any respect for any reason, the validity and enforceability of any such provision in any other respect and of the remaining provisions of this Agreement shall not be impaired. This Agreement shall be binding on and inure to the benefit of the parties and their heirs, personal representatives, successors, and assigns.</p>

            <h2 className="font-bold text-base text-black">21. Force Majeure</h2>
            <p className="text-sm text-black mb-4">Company will not be liable for or be considered to be in breach of or default under this Agreement on account of, any delay or failure to perform as required by this Agreement as a result of any cause or condition beyond Company’s reasonable control.</p>

            <h2 className="font-bold text-base text-black">22. Defense and Indemnification</h2>
            <p className="text-sm text-black mb-4">
              In addition to the other provisions of this Agreement, you agree to defend Company from any actual or threatened third party claim arising out of or based upon your use of the Services, your failure to comply with any of the provisions of applicable law, and your breach of any of the provisions of this Agreement. In addition, you agree to indemnify, and hold harmless Company from and against: (a) all damages, costs, and attorneys’ fees finally awarded against Company in any proceeding under this section; (b) all out-of-pocket costs (including reasonable attorneys’ fees) reasonably incurred by Company in connection with the defense of such proceeding (other than when you have accepted defense of such claim); and (c) if any proceeding arising under this section is settled, any
              amounts to any third party agreed to by you in settlement of any such claims.
            </p>
          </div>
        </div>
      </div>
    </>

  );
};

export default Terms;
